import { Field, DataType } from '@shared/types/fieldBuilder';

/**
 * 生成唯一标识符
 * Generate a unique identifier
 *
 * @returns {string} 唯一ID字符串，格式为: timestamp-randomstring
 *
 * @example
 * ```ts
 * const id = generateId();
 * // id format: "timestamp-randomstring"
 * ```
 */
export function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

/**
 * 生成HQL语句
 * Generate HQL statement based on fields and event name
 *
 * @param {Field[]} fields - 字段配置数组
 * @param {string} eventName - 事件名称
 * @param {'view' | 'procedure'} mode - 生成模式: 'view' 或 'procedure'
 * @returns {string} 生成的HQL语句
 *
 * @example
 * ```ts
 * const fields: Field[] = [
 *   { name: 'user_id', alias: 'userId', type: 'base' }
 * ];
 * const hql = generateHQL(fields, 'login', 'view');
 * // hql contains the generated HQL statement
 * ```
 */
export function generateHQL(fields: Field[], eventName: string, mode: 'view' | 'procedure'): string {
  const fieldList = fields.map(f => f.alias || f.name).join(',\n    ');

  if (mode === 'view') {
    return `-- HQL View Generated by Field Builder
CREATE OR REPLACE VIEW dwd_${eventName}_di AS
SELECT
    ${fieldList}
FROM ieu_ods.ods_${eventName}_all_view
WHERE ds = '\${bizdate}'
;`;
  } else {
    return `-- HQL Procedure Generated by Field Builder
CREATE PROCEDURE generate_${eventName}_di()
BEGIN
  -- TODO: Implement procedure logic
END;`;
  }
}

/**
 * 验证字段配置
 * Validate field configuration
 *
 * @param {Partial<Field>} field - 部分字段配置对象
 * @returns {string[]} 错误消息数组，如果验证通过则返回空数组
 *
 * @example
 * ```ts
 * const field: Partial<Field> = { name: '', alias: '' };
 * const errors = validateField(field);
 * // errors: ["字段名不能为空", "字段别名不能为空"]
 *
 * const validField: Partial<Field> = { name: 'user_id', alias: 'userId', type: 'base' };
 * const errors2 = validateField(validField);
 * // errors2: []
 * ```
 */
export function validateField(field: Partial<Field>): string[] {
  const errors: string[] = [];

  if (!field.name || field.name.trim() === '') {
    errors.push('字段名不能为空');
  }

  if (!field.alias || field.alias.trim() === '') {
    errors.push('字段别名不能为空');
  }

  if (field.type === 'fixed' && !field.fixedValue) {
    errors.push('固定值字段必须提供值');
  }

  return errors;
}
