// @ts-nocheck - TypeScript strict mode disabled for test files
/**
 * fieldBuilder.test.ts
 * Unit tests for field builder utilities
 */

import { describe, it, expect } from 'vitest';
import { generateId, generateHQL, validateField } from './fieldBuilder';
import { Field } from '@shared/types/fieldBuilder';

describe('fieldBuilder', () => {
  describe('generateId', () => {
    it('should generate unique IDs', () => {
      const id1 = generateId();
      const id2 = generateId();
      expect(id1).not.toBe(id2);
    });

    it('should generate string IDs', () => {
      const id = generateId();
      expect(typeof id).toBe('string');
    });

    it('should include timestamp in ID', () => {
      const before = Date.now();
      const id = generateId();
      const after = Date.now();

      const timestamp = parseInt(id.split('-')[0]);
      expect(timestamp).toBeGreaterThanOrEqual(before);
      expect(timestamp).toBeLessThanOrEqual(after);
    });

    it('should include random string in ID', () => {
      const id = generateId();
      const parts = id.split('-');
      expect(parts.length).toBe(2);
      expect(parts[1].length).toBeGreaterThan(0);
    });

    it('should generate IDs with correct format', () => {
      const id = generateId();
      expect(id).toMatch(/^\d+-[a-z0-9]+$/);
    });

    it('should generate multiple IDs quickly', () => {
      const ids = new Set();
      for (let i = 0; i < 1000; i++) {
        ids.add(generateId());
      }
      expect(ids.size).toBe(1000); // All unique
    });
  });

  describe('generateHQL', () => {
    it('should generate view mode HQL', () => {
      const fields: Field[] = [
        { name: 'ds', alias: 'ds', type: 'base' },
        { name: 'role_id', alias: 'role_id', type: 'base' }
      ];
      const hql = generateHQL(fields, 'login', 'view');

      expect(hql).toContain('CREATE OR REPLACE VIEW');
      expect(hql).toContain('dwd_login_di');
      expect(hql).toContain('SELECT');
      expect(hql).toContain('ds');
      expect(hql).toContain('role_id');
      expect(hql).toContain('ieu_ods.ods_login_all_view');
      expect(hql).toContain('${bizdate}');
    });

    it('should generate procedure mode HQL', () => {
      const fields: Field[] = [
        { name: 'ds', alias: 'ds', type: 'base' }
      ];
      const hql = generateHQL(fields, 'login', 'procedure');

      expect(hql).toContain('CREATE PROCEDURE');
      expect(hql).toContain('generate_login_di');
      expect(hql).not.toContain('CREATE OR REPLACE VIEW');
    });

    it('should include comment header', () => {
      const fields: Field[] = [
        { name: 'ds', alias: 'ds', type: 'base' }
      ];
      const hqlView = generateHQL(fields, 'login', 'view');
      const hqlProc = generateHQL(fields, 'login', 'procedure');

      expect(hqlView).toContain('-- HQL View Generated by Field Builder');
      expect(hqlProc).toContain('-- HQL Procedure Generated by Field Builder');
    });

    it('should use alias when available', () => {
      const fields: Field[] = [
        { name: 'role_id', alias: 'roleId', type: 'base' }
      ];
      const hql = generateHQL(fields, 'login', 'view');

      expect(hql).toContain('roleId');
      expect(hql).not.toContain('role_id');
    });

    it('should use name when alias is not available', () => {
      const fields: Field[] = [
        { name: 'role_id', alias: '', type: 'base' }
      ] as Field[];
      const hql = generateHQL(fields, 'login', 'view');

      expect(hql).toContain('role_id');
    });

    it('should handle multiple fields', () => {
      const fields: Field[] = [
        { name: 'ds', alias: 'ds', type: 'base' },
        { name: 'role_id', alias: 'role_id', type: 'base' },
        { name: 'zone_id', alias: 'zone_id', type: 'param', json_path: '$.zoneId' }
      ];
      const hql = generateHQL(fields, 'login', 'view');

      expect(hql).toContain('ds');
      expect(hql).toContain('role_id');
      expect(hql).toContain('zone_id');
    });

    it('should handle empty fields array', () => {
      const fields: Field[] = [];
      const hql = generateHQL(fields, 'login', 'view');

      expect(hql).toContain('CREATE OR REPLACE VIEW');
      expect(hql).toContain('SELECT');
    });

    it('should format field list with proper indentation', () => {
      const fields: Field[] = [
        { name: 'ds', alias: 'ds', type: 'base' },
        { name: 'role_id', alias: 'role_id', type: 'base' }
      ];
      const hql = generateHQL(fields, 'login', 'view');

      expect(hql).toContain('    ds'); // Indented fields
    });

    it('should include WHERE clause with bizdate variable', () => {
      const fields: Field[] = [
        { name: 'ds', alias: 'ds', type: 'base' }
      ];
      const hql = generateHQL(fields, 'login', 'view');

      expect(hql).toContain("WHERE ds = '${bizdate}'");
    });

    it('should escape underscores in event name', () => {
      const fields: Field[] = [
        { name: 'ds', alias: 'ds', type: 'base' }
      ];
      const hql = generateHQL(fields, 'user_level_up', 'view');

      expect(hql).toContain('dwd_user_level_up_di');
      expect(hql).toContain('ods_user_level_up_all_view');
    });
  });

  describe('validateField', () => {
    it('should return empty array for valid field', () => {
      const field: Partial<Field> = {
        name: 'role_id',
        alias: 'roleId',
        type: 'base'
      };
      const errors = validateField(field);
      expect(errors).toEqual([]);
    });

    it('should detect empty name', () => {
      const field: Partial<Field> = {
        name: '',
        alias: 'roleId',
        type: 'base'
      };
      const errors = validateField(field);
      expect(errors).toContain('字段名不能为空');
    });

    it('should detect whitespace-only name', () => {
      const field: Partial<Field> = {
        name: '   ',
        alias: 'roleId',
        type: 'base'
      };
      const errors = validateField(field);
      expect(errors).toContain('字段名不能为空');
    });

    it('should detect missing name', () => {
      const field: Partial<Field> = {
        alias: 'roleId',
        type: 'base'
      };
      const errors = validateField(field);
      expect(errors).toContain('字段名不能为空');
    });

    it('should detect empty alias', () => {
      const field: Partial<Field> = {
        name: 'role_id',
        alias: '',
        type: 'base'
      };
      const errors = validateField(field);
      expect(errors).toContain('字段别名不能为空');
    });

    it('should detect whitespace-only alias', () => {
      const field: Partial<Field> = {
        name: 'role_id',
        alias: '   ',
        type: 'base'
      };
      const errors = validateField(field);
      expect(errors).toContain('字段别名不能为空');
    });

    it('should detect missing alias', () => {
      const field: Partial<Field> = {
        name: 'role_id',
        type: 'base'
      };
      const errors = validateField(field);
      expect(errors).toContain('字段别名不能为空');
    });

    it('should detect missing fixed value for fixed type', () => {
      const field: Partial<Field> = {
        name: 'game_id',
        alias: 'gameId',
        type: 'fixed'
      };
      const errors = validateField(field);
      expect(errors).toContain('固定值字段必须提供值');
    });

    it('should not require fixed value for non-fixed types', () => {
      const field: Partial<Field> = {
        name: 'role_id',
        alias: 'roleId',
        type: 'base'
      };
      const errors = validateField(field);
      expect(errors).not.toContain('固定值字段必须提供值');
    });

    it('should allow fixed type with value', () => {
      const field: Partial<Field> = {
        name: 'game_id',
        alias: 'gameId',
        type: 'fixed',
        fixedValue: '10000147'
      };
      const errors = validateField(field);
      expect(errors).toEqual([]);
    });

    it('should collect multiple errors', () => {
      const field: Partial<Field> = {
        name: '',
        alias: '',
        type: 'fixed'
      };
      const errors = validateField(field);
      expect(errors.length).toBe(3); // name, alias, fixedValue
      expect(errors).toContain('字段名不能为空');
      expect(errors).toContain('字段别名不能为空');
      expect(errors).toContain('固定值字段必须提供值');
    });

    it('should handle empty field object', () => {
      const field: Partial<Field> = {};
      const errors = validateField(field);
      expect(errors.length).toBeGreaterThan(0);
      expect(errors).toContain('字段名不能为空');
      expect(errors).toContain('字段别名不能为空');
    });

    it('should validate param type fields', () => {
      const field: Partial<Field> = {
        name: 'zone_id',
        alias: 'zoneId',
        type: 'param',
        json_path: '$.zoneId'
      };
      const errors = validateField(field);
      expect(errors).toEqual([]);
    });

    it('should validate custom type fields', () => {
      const field: Partial<Field> = {
        name: 'custom_field',
        alias: 'customField',
        type: 'custom',
        expression: 'some expression'
      };
      const errors = validateField(field);
      expect(errors).toEqual([]);
    });
  });

  describe('real-world scenarios', () => {
    it('should generate HQL for login event', () => {
      const fields: Field[] = [
        { name: 'ds', alias: 'ds', type: 'base' },
        { name: 'role_id', alias: 'roleId', type: 'base' },
        { name: 'account_id', alias: 'accountId', type: 'base' },
        { name: 'zone_id', alias: 'zoneId', type: 'param', json_path: '$.zoneId' },
        { name: 'level', alias: 'level', type: 'param', json_path: '$.level' },
        { name: 'game_id', alias: 'gameId', type: 'fixed', fixedValue: '10000147' }
      ];

      const hql = generateHQL(fields, 'login', 'view');

      expect(hql).toContain('CREATE OR REPLACE VIEW dwd_login_di');
      expect(hql).toContain('FROM ieu_ods.ods_login_all_view');
      expect(hql).toContain('ds');
      expect(hql).toContain('roleId');
      expect(hql).toContain('accountId');
      expect(hql).toContain('zoneId');
      expect(hql).toContain('level');
      expect(hql).toContain('gameId');
    });

    it('should validate complete field configuration', () => {
      const fields: Partial<Field>[] = [
        {
          name: 'ds',
          alias: 'ds',
          type: 'base'
        },
        {
          name: 'role_id',
          alias: 'roleId',
          type: 'base'
        },
        {
          name: 'game_id',
          alias: 'gameId',
          type: 'fixed',
          fixedValue: '10000147'
        }
      ];

      fields.forEach(field => {
        const errors = validateField(field);
        expect(errors).toEqual([]);
      });
    });

    it('should generate unique IDs for multiple fields', () => {
      const ids = new Set();
      for (let i = 0; i < 100; i++) {
        ids.add(generateId());
      }
      expect(ids.size).toBe(100);
    });
  });

  describe('edge cases', () => {
    it('should handle field with special characters in name', () => {
      const field: Partial<Field> = {
        name: 'user_id_custom',
        alias: 'userIdCustom',
        type: 'base'
      };
      const errors = validateField(field);
      expect(errors).toEqual([]);
    });

    it('should handle very long field names', () => {
      const field: Partial<Field> = {
        name: 'a'.repeat(1000),
        alias: 'b'.repeat(1000),
        type: 'base'
      };
      const errors = validateField(field);
      expect(errors).toEqual([]);
    });

    it('should handle fields with unicode characters', () => {
      const field: Partial<Field> = {
        name: '用户ID',
        alias: 'userId',
        type: 'base'
      };
      const errors = validateField(field);
      expect(errors).toEqual([]);
    });

    it('should generate IDs with high uniqueness', () => {
      const ids = new Set();
      for (let i = 0; i < 10000; i++) {
        ids.add(generateId());
      }
      // In practice, should be 10000 unique, but we check for very high percentage
      expect(ids.size).toBeGreaterThan(9990);
    });
  });
});
