# ⚠️ PERFORMANCE ISSUE: N+1 query detected in this file
# TODO: Refactor to use JOIN or prefetch pattern
# See: docs/reports/2026-03-05/PERFORMANCE-OPTIMIZATION-DETAILED-REPORT.md

"""
DML生成器单元测试

测试DML生成器的各种功能: 
1. INSERT OVERWRITE TABLE语句生成
2. INSERT OVERWRITE DIRECTORY语句生成
3. 参数验证
4. 注释生成
5. 工厂模式
"""

import pytest
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

from backend.services.hql.core.dml_generator import (
    DMLGenerator,
    DMLBuilderFactory,
    generate_insert_overwrite,
)


class TestDMLGenerator:
    """DML生成器基础测试"""

    def test_generate_insert_overwrite_basic(self):
        """测试: 基本INSERT OVERWRITE语句生成"""
        generator = DMLGenerator()

        dml = generator.generate_insert_overwrite(
            target_table="dwd.v_dwd_10000147_login_di",
            source_query="SELECT role_id, account_id FROM ods_table",
            partition_ds="20260217",
        )

        assert "INSERT OVERWRITE TABLE dwd.v_dwd_10000147_login_di" in dml
        assert "PARTITION (ds='20260217')" in dml
        assert "SELECT role_id, account_id FROM ods_table" in dml

    def test_generate_insert_overwrite_with_comments(self):
        """测试: 带注释的INSERT OVERWRITE语句"""
        generator = DMLGenerator()

        dml = generator.generate_insert_overwrite(
            target_table="dwd.v_dwd_10000147_login_di",
            source_query="SELECT role_id FROM ods_table",
            partition_ds="20260217",
            include_comments=True,
        )

        assert "-- Generated by Event2Table DML Generator" in dml
        assert "-- Target Table: dwd.v_dwd_10000147_login_di" in dml
        assert "-- Partition: ds='20260217'" in dml
        assert "INSERT OVERWRITE TABLE" in dml

    def test_generate_insert_overwrite_without_comments(self):
        """测试: 不带注释的INSERT OVERWRITE语句"""
        generator = DMLGenerator()

        dml = generator.generate_insert_overwrite(
            target_table="dwd.v_dwd_10000147_login_di",
            source_query="SELECT role_id FROM ods_table",
            partition_ds="20260217",
            include_comments=False,
        )

        assert "--" not in dml
        assert "INSERT OVERWRITE TABLE" in dml

    def test_generate_insert_overwrite_with_dynamic_partition(self):
        """测试: 使用动态分区变量(${bizdate})"""
        generator = DMLGenerator()

        dml = generator.generate_insert_overwrite(
            target_table="dwd.v_dwd_10000147_login_di",
            source_query="SELECT * FROM staging_table",
            partition_ds="${bizdate}",
        )

        assert "PARTITION (ds='${bizdate}')" in dml
        assert "INSERT OVERWRITE TABLE" in dml

    def test_generate_insert_overwrite_with_ds_variable(self):
        """测试: 使用${ds}变量"""
        generator = DMLGenerator()

        dml = generator.generate_insert_overwrite(
            target_table="dwd.v_dwd_10000147_login_di",
            source_query="SELECT * FROM staging_table",
            partition_ds="${ds}",
        )

        assert "PARTITION (ds='${ds}')" in dml

    def test_generate_insert_overwrite_multiline_query(self):
        """测试: 多行源查询"""
        generator = DMLGenerator()

        source_query = """SELECT
  role_id,
  account_id,
  get_json_object(params, '$.zone_id') AS zone_id
FROM ods_table
WHERE ds = '${bizdate}'"""

        dml = generator.generate_insert_overwrite(
            target_table="dwd.v_dwd_10000147_login_di",
            source_query=source_query,
            partition_ds="20260217",
        )

        assert "INSERT OVERWRITE TABLE" in dml
        assert "PARTITION (ds='20260217')" in dml
        assert "role_id," in dml
        assert "get_json_object(params, '$.zone_id')" in dml


class TestDMLGeneratorInsertDirectory:
    """INSERT OVERWRITE DIRECTORY测试"""

    def test_generate_insert_overwrite_directory_basic(self):
        """测试: 基本INSERT OVERWRITE DIRECTORY语句"""
        generator = DMLGenerator()

        dml = generator.generate_insert_overwrite_directory(
            target_directory="hdfs:///data/export/20260217", source_query="SELECT * FROM dwd_table"
        )

        assert "INSERT OVERWRITE DIRECTORY 'hdfs:///data/export/20260217'" in dml
        assert "FIELDS TERMINATED BY" in dml
        assert "LINES TERMINATED BY" in dml
        assert "STORED AS TEXTFILE" in dml
        assert "SELECT * FROM dwd_table" in dml

    def test_generate_insert_overwrite_directory_with_format(self):
        """测试: 指定文件格式(PARQUET)"""
        generator = DMLGenerator()

        dml = generator.generate_insert_overwrite_directory(
            target_directory="hdfs:///data/export/20260217",
            source_query="SELECT * FROM dwd_table",
            file_format="PARQUET",
        )

        assert "STORED AS PARQUET" in dml

    def test_generate_insert_overwrite_directory_with_custom_delimiters(self):
        """测试: 自定义分隔符"""
        generator = DMLGenerator()

        dml = generator.generate_insert_overwrite_directory(
            target_directory="hdfs:///data/export/20260217",
            source_query="SELECT * FROM dwd_table",
            field_delim=",",
            line_delim="\\n",
        )

        assert "FIELDS TERMINATED BY ','" in dml
        assert "LINES TERMINATED BY '\\n'" in dml


class TestDMLGeneratorValidation:
    """参数验证测试"""

    def test_validate_empty_target_table(self):
        """测试: 空目标表名验证"""
        generator = DMLGenerator()

        with pytest.raises(ValueError, match="target_table cannot be empty"):
            generator.generate_insert_overwrite(
                target_table="", source_query="SELECT * FROM table", partition_ds="20260217"
            )

    def test_validate_invalid_table_format(self):
        """测试: 无效的表名格式(缺少database前缀)"""
        generator = DMLGenerator()

        with pytest.raises(ValueError, match="must be in format 'database.table'"):
            generator.generate_insert_overwrite(
                target_table="table_name",
                source_query="SELECT * FROM table",
                partition_ds="20260217",
            )

    def test_validate_dangerous_keywords_in_table(self):
        """测试: 表名中的危险关键字"""
        generator = DMLGenerator()

        with pytest.raises(ValueError, match="Dangerous SQL keyword"):
            generator.generate_insert_overwrite(
                target_table="dwd.DROP;TABLE",
                source_query="SELECT * FROM table",
                partition_ds="20260217",
            )

    def test_validate_empty_source_query(self):
        """测试: 空源查询验证"""
        generator = DMLGenerator()

        with pytest.raises(ValueError, match="source_query cannot be empty"):
            generator.generate_insert_overwrite(
                target_table="dwd.table", source_query="", partition_ds="20260217"
            )

    def test_validate_non_select_query(self):
        """测试: 非SELECT查询验证"""
        generator = DMLGenerator()

        with pytest.raises(ValueError, match="Dangerous operation 'UPDATE'"):
            generator.generate_insert_overwrite(
                target_table="dwd.table",
                source_query="UPDATE table SET x=1",
                partition_ds="20260217",
            )

    def test_validate_dangerous_operations_in_query(self):
        """测试: 源查询中的危险操作"""
        generator = DMLGenerator()

        with pytest.raises(ValueError, match="Dangerous operation"):
            generator.generate_insert_overwrite(
                target_table="dwd.table",
                source_query="SELECT * FROM table; DROP TABLE other",
                partition_ds="20260217",
            )

    def test_validate_empty_partition_ds(self):
        """测试: 空分区日期验证"""
        generator = DMLGenerator()

        with pytest.raises(ValueError, match="partition_ds cannot be empty"):
            generator.generate_insert_overwrite(
                target_table="dwd.table", source_query="SELECT * FROM table", partition_ds=""
            )

    def test_validate_invalid_date_format(self):
        """测试: 无效的日期格式"""
        generator = DMLGenerator()

        with pytest.raises(ValueError, match="must be in format YYYYMMDD"):
            generator.generate_insert_overwrite(
                target_table="dwd.table",
                source_query="SELECT * FROM table",
                partition_ds="2026-02-17",
            )

    def test_validate_invalid_date(self):
        """测试: 无效的日期(20260230不存在)"""
        generator = DMLGenerator()

        with pytest.raises(ValueError, match="contains invalid date"):
            generator.generate_insert_overwrite(
                target_table="dwd.table",
                source_query="SELECT * FROM table",
                partition_ds="20260230",
            )


class TestDMLBuilderFactory:
    """DML工厂模式测试"""

    def test_create_etl_dml(self):
        """测试: 创建标准ETL DML语句"""
        dml = DMLBuilderFactory.create_etl_dml(
            dwd_prefix="dwd",
            game_gid=10000147,
            event_name="login",
            source_query="SELECT role_id FROM ods_table",
            partition_ds="20260217",
        )

        assert "INSERT OVERWRITE TABLE dwd.v_dwd_10000147_login_di" in dml
        assert "PARTITION (ds='20260217')" in dml
        assert "SELECT role_id FROM ods_table" in dml

    def test_create_batch_insert_single_query(self):
        """测试: 单查询批量插入"""
        dml = DMLBuilderFactory.create_batch_insert(
            target_table="dwd.table",
            source_queries=["SELECT * FROM table1"],
            partition_ds="20260217",
        )

        assert "INSERT OVERWRITE TABLE dwd.table" in dml
        assert "SELECT * FROM table1" in dml
        assert "UNION ALL" not in dml

    def test_create_batch_insert_multiple_queries(self):
        """测试: 多查询批量插入(UNION ALL)"""
        dml = DMLBuilderFactory.create_batch_insert(
            target_table="dwd.table",
            source_queries=["SELECT * FROM table1", "SELECT * FROM table2", "SELECT * FROM table3"],
            partition_ds="20260217",
        )

        assert "INSERT OVERWRITE TABLE dwd.table" in dml
        assert "UNION ALL" in dml
        assert "SELECT * FROM table1" in dml
        assert "SELECT * FROM table2" in dml
        assert "SELECT * FROM table3" in dml

    def test_create_batch_insert_empty_queries(self):
        """测试: 空查询列表验证"""
        with pytest.raises(ValueError, match="source_queries cannot be empty"):
            DMLBuilderFactory.create_batch_insert(
                target_table="dwd.table", source_queries=[], partition_ds="20260217"
            )


class TestConvenienceFunctions:
    """便捷函数测试"""

    def test_generate_insert_overwrite_function(self):
        """测试: generate_insert_overwrite便捷函数"""
        dml = generate_insert_overwrite(
            target_table="dwd.v_dwd_10000147_login_di",
            source_query="SELECT role_id FROM ods_table",
            partition_ds="20260217",
        )

        assert "INSERT OVERWRITE TABLE" in dml
        assert "PARTITION (ds='20260217')" in dml

    def test_generate_insert_overwrite_with_options(self):
        """测试: 带额外选项的便捷函数"""
        dml = generate_insert_overwrite(
            target_table="dwd.v_dwd_10000147_login_di",
            source_query="SELECT role_id FROM ods_table",
            partition_ds="20260217",
            include_comments=False,
        )

        assert "--" not in dml
        assert "INSERT OVERWRITE TABLE" in dml


class TestEdgeCases:
    """边界情况测试"""

    def test_source_query_with_leading_whitespace(self):
        """测试: 带前导空白的源查询"""
        generator = DMLGenerator()

        dml = generator.generate_insert_overwrite(
            target_table="dwd.table",
            source_query="  \n  SELECT role_id FROM ods_table",
            partition_ds="20260217",
        )

        assert "SELECT role_id FROM ods_table" in dml

    def test_source_query_with_comments(self):
        """测试: 带注释的源查询"""
        generator = DMLGenerator()

        source_query = """-- This is a comment
SELECT role_id FROM ods_table"""

        dml = generator.generate_insert_overwrite(
            target_table="dwd.table", source_query=source_query, partition_ds="20260217"
        )

        assert "-- This is a comment" in dml
        assert "SELECT role_id FROM ods_table" in dml

    def test_source_query_with_blank_lines(self):
        """测试: 带空白行的源查询"""
        generator = DMLGenerator()

        source_query = """SELECT
  role_id,

  account_id

FROM ods_table"""

        dml = generator.generate_insert_overwrite(
            target_table="dwd.table", source_query=source_query, partition_ds="20260217"
        )

        # 空白行应该被压缩
        assert "role_id," in dml
        assert "account_id" in dml
        assert "FROM ods_table" in dml

    def test_various_date_formats(self):
        """测试: 各种有效日期格式"""
        generator = DMLGenerator()

        valid_dates = [
            "20260101",  # 年初
            "20261231",  # 年末
            "20260228",  # 非闰年2月
            "20240229",  # 闰年2月
        ]

        for date in valid_dates:
            dml = generator.generate_insert_overwrite(
                target_table="dwd.table", source_query="SELECT * FROM table", partition_ds=date
            )
            assert f"PARTITION (ds='{date}')" in dml


class TestRealWorldScenarios:
    """真实场景测试"""

    def test_complete_etl_workflow(self):
        """测试: 完整ETL工作流场景"""
        generator = DMLGenerator()

        # 模拟真实的源查询(从HQL生成器输出)
        source_query = """SELECT
  ds,
  role_id,
  account_id,
  utdid,
  get_json_object(params, '$.zoneId') AS zone_id,
  get_json_object(params, '$.level') AS level
FROM ieu_ods.ods_10000147_all_view
WHERE ds = '${bizdate}'"""

        dml = generator.generate_insert_overwrite(
            target_table="dwd.v_dwd_10000147_login_di",
            source_query=source_query,
            partition_ds="${bizdate}",
            include_comments=True,
        )

        # 验证关键字段
        assert "INSERT OVERWRITE TABLE dwd.v_dwd_10000147_login_di" in dml
        assert "PARTITION (ds='${bizdate}')" in dml
        assert "role_id," in dml
        assert "get_json_object(params, '$.zoneId')" in dml
        assert "-- Generated by Event2Table DML Generator" in dml

    def test_multiple_events_union(self):
        """测试: 多事件UNION场景"""
        generator = DMLGenerator()

        # 模拟UNION ALL查询
        source_query = """SELECT role_id, account_id, 'login' AS event_type
FROM ods_login
WHERE ds = '${bizdate}'
UNION ALL
SELECT role_id, account_id, 'logout' AS event_type
FROM ods_logout
WHERE ds = '${bizdate}'"""

        dml = generator.generate_insert_overwrite(
            target_table="dwd.v_dwd_10000147_all_events_di",
            source_query=source_query,
            partition_ds="20260217",
        )

        assert "UNION ALL" in dml
        assert "'login' AS event_type" in dml
        assert "'logout' AS event_type" in dml


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
