"""
DML Generator与HQL Generator集成测试

演示完整的DDL + DML工作流
"""

import pytest
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

from backend.services.hql.core.generator import HQLGenerator
from backend.services.hql.core.dml_generator import DMLGenerator, DMLBuilderFactory
from backend.services.hql.models.event import Event, Field, FieldType


class TestDMLHQLIntegration:
    """DML与HQL生成器集成测试"""

    def test_complete_ddl_dml_workflow(self):
        """测试: 完整的DDL + DML工作流"""

        # 1. 生成DDL(使用HQL Generator生成SELECT语句)
        hql_generator = HQLGenerator()

        event = Event(name="login", table_name="ieu_ods.ods_10000147_all_view")

        fields = [
            Field(name="ds", type=FieldType.BASE),
            Field(name="role_id", type=FieldType.BASE),
            Field(name="account_id", type=FieldType.BASE),
            Field(name="utdid", type=FieldType.BASE),
            Field(name="zone_id", type=FieldType.PARAM, json_path="$.zoneId"),
            Field(name="level", type=FieldType.PARAM, json_path="$.level"),
        ]

        # 生成SELECT查询
        select_query = hql_generator.generate(events=[event], fields=fields, conditions=[])

        # 2. 生成DML(使用DML Generator生成INSERT OVERWRITE)
        dml_generator = DMLGenerator()

        dml = dml_generator.generate_insert_overwrite(
            target_table="dwd.v_dwd_10000147_login_di",
            source_query=select_query,
            partition_ds="${bizdate}",
            include_comments=True,
        )

        # 3. 验证完整输出
        assert "INSERT OVERWRITE TABLE dwd.v_dwd_10000147_login_di" in dml
        assert "PARTITION (ds='${bizdate}')" in dml
        assert "SELECT" in dml
        assert "`role_id`," in dml
        assert "get_json_object(params, '$.zoneId')" in dml
        assert "-- Generated by Event2Table DML Generator" in dml

    def test_factory_pattern_workflow(self):
        """测试: 使用工厂模式的完整工作流"""

        # 1. 生成SELECT查询
        hql_generator = HQLGenerator()

        event = Event(name="purchase", table_name="ieu_ods.ods_10000147_all_view")

        fields = [
            Field(name="role_id", type=FieldType.BASE),
            Field(name="amount", type=FieldType.PARAM, json_path="$.amount"),
        ]

        select_query = hql_generator.generate(events=[event], fields=fields, conditions=[])

        # 2. 使用工厂模式生成DML
        dml = DMLBuilderFactory.create_etl_dml(
            dwd_prefix="dwd",
            game_gid=10000147,
            event_name="purchase",
            source_query=select_query,
            partition_ds="20260217",
        )

        # 3. 验证
        assert "INSERT OVERWRITE TABLE dwd.v_dwd_10000147_purchase_di" in dml
        assert "PARTITION (ds='20260217')" in dml
        assert "get_json_object(params, '$.amount')" in dml

    def test_multi_event_union_workflow(self):
        """测试: 多事件UNION + DML工作流"""

        # 1. 生成UNION ALL查询
        hql_generator = HQLGenerator()

        events = [
            Event(name="login", table_name="ieu_ods.ods_10000147_login_view"),
            Event(name="logout", table_name="ieu_ods.ods_10000147_logout_view"),
        ]

        fields = [
            Field(name="role_id", type=FieldType.BASE),
            Field(name="event_time", type=FieldType.BASE),
        ]

        union_query = hql_generator.generate(
            events=events, fields=fields, conditions=[], mode="union"
        )

        # 2. 生成DML
        dml_generator = DMLGenerator()

        dml = dml_generator.generate_insert_overwrite(
            target_table="dwd.v_dwd_10000147_all_events_di",
            source_query=union_query,
            partition_ds="${bizdate}",
        )

        # 3. 验证UNION和INSERT
        assert "INSERT OVERWRITE TABLE" in dml
        assert "UNION ALL" in dml
        assert "PARTITION (ds='${bizdate}')" in dml

    def test_export_to_directory_workflow(self):
        """测试: 导出到文件系统的完整工作流"""

        # 1. 生成SELECT查询
        hql_generator = HQLGenerator()

        event = Event(name="login", table_name="dwd.v_dwd_10000147_login_di")

        fields = [
            Field(name="role_id", type=FieldType.BASE),
            Field(name="account_id", type=FieldType.BASE),
        ]

        select_query = hql_generator.generate(events=[event], fields=fields, conditions=[])

        # 2. 生成导出DML
        dml_generator = DMLGenerator()

        dml = dml_generator.generate_insert_overwrite_directory(
            target_directory="hdfs:///data/export/20260217/login_events",
            source_query=select_query,
            file_format="PARQUET",
            field_delim=",",
        )

        # 3. 验证
        assert "INSERT OVERWRITE DIRECTORY" in dml
        assert "hdfs:///data/export/20260217/login_events" in dml
        assert "STORED AS PARQUET" in dml
        assert "FIELDS TERMINATED BY ','" in dml


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
