// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/test/api_contract_test.py --generate-types
// This file contains TypeScript type definitions generated from backend API routes


export interface Game {
  id: number;
  gid: number;
  name: string;
  ods_db: string;
  created_at: string;
}

export interface GameResponse {
  data: Game;
  success: boolean;
  message?: string;
  timestamp?: string;
}


export interface Event {
  id: number;
  event_name: string;
  display_name: string;
  game_gid: number;
  event_type: 'user' | 'system' | 'auto';
  created_at: string;
}

export interface EventResponse {
  data: Event;
  success: boolean;
  message?: string;
  timestamp?: string;
}


export interface Parameter {
  id: number;
  param_name: string;
  param_name_cn: string;
  param_type: 'string' | 'int' | 'float' | 'boolean' | 'json';
  game_gid: number | null;
}

export interface ParameterResponse {
  data: Parameter;
  success: boolean;
  message?: string;
  timestamp?: string;
}


// Generic API response types
export interface APIResponse<T> {
  data: T;
  success: boolean;
  message?: string;
  timestamp?: string;
}

export interface PaginatedResponse<T> extends APIResponse<T[]> {
  pagination?: {
    page: number;
    page_size: number;
    total: number;
    total_pages: number;
  };
}

// Type guard utilities
export function isApiResponse(data: unknown): data is APIResponse<unknown> {
  return typeof data === 'object' && data !== null &&
         'data' in data &&
         'success' in data &&
         typeof (data as any).success === 'boolean';
}
